// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using balance_dp.Models;

namespace balance_dp.Migrations
{
    [DbContext(typeof(DPContext))]
    partial class DPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("balance_dp.Models.BlastFurnace", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("list1_C20_Dailyproductivity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C21_CockCUMsuption")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C23_EffectVolume")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C24_HeatLoses_ofBlastFurnace")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("BlastFurnace");
                });

            modelBuilder.Entity("balance_dp.Models.BlastFurnaceGas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("list1_C61_GasTemperature")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C62_CO2_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C63_CO_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C64_H2_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C66_DustExit")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C67_FeO_Capacity")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("BlastFurnaceGases");
                });

            modelBuilder.Entity("balance_dp.Models.BlowingParams", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("list1_C32_BlowingConsumptionPerMinute")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C33_HotBlowingTemperature")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C34_BlowingMoistureTechReport")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C35_NaturalBlowingConsumption")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C37_PersentOxygenInBlowing")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C38_SpecificConsuptionNaturalGas")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C39_CH4Consuption")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C40_C2H6Comsuption")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C41_C3H8Comsuption")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C42_CO2Comsuption")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C43_C_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C44_H2_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C46_limestoneWaterCapacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C47_limestoneWeightLoss")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("BlowingParams");
                });

            modelBuilder.Entity("balance_dp.Models.COCKsAsh", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("list2_A46_Fe")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_B46_Cao")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_C46_Sio2")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_D46_Al2O3")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_E46_MgO")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_F46_P")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("COCKsAshes");
                });

            modelBuilder.Entity("balance_dp.Models.COCKsComposition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("list2_A42_AhsCocks")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_B42_SulfurCocks")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_C42_LiquidCocks")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("COCKsCompositions");
                });

            modelBuilder.Entity("balance_dp.Models.COCKsParamsPersent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("COCKsAshId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("COCKsCompositionid")
                        .HasColumnType("INTEGER");

                    b.Property<float>("list1_C29_WaterCOCKs")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C30_FeoCOCKs")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.HasIndex("COCKsAshId");

                    b.HasIndex("COCKsCompositionid");

                    b.ToTable("COCKsParamsPersents");
                });

            modelBuilder.Entity("balance_dp.Models.CastIronElementsPercent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("list1_C10_Mn")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C11_S")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C12_P")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C13_Ti")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C14_Cr")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C15_V")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C17_CastIronTemperature")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C18_CastIronHeatCapacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C9_Si")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_С16_C")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("CastIronElementsPercents");
                });

            modelBuilder.Entity("balance_dp.Models.DPInputData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputData2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputIndicatorsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NAME")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InputData2Id");

                    b.HasIndex("InputIndicatorsId");

                    b.ToTable("Inputs");
                });

            modelBuilder.Entity("balance_dp.Models.Flus", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FluospatID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LimestoneID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuartziteID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReserveID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SlugID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("FluospatID");

                    b.HasIndex("LimestoneID");

                    b.HasIndex("QuartziteID");

                    b.HasIndex("ReserveID");

                    b.HasIndex("SlugID");

                    b.ToTable("Flus");
                });

            modelBuilder.Entity("balance_dp.Models.FlusModels", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("list2_B33flusConsuption")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_C33_CaO_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_D33_SiO2_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_E33_Al2O3_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_F33_MgO_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_G33_TiO2Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_H33_MnO_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_I33_P_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list2_J33_S_Capacity")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("FlusModels");
                });

            modelBuilder.Entity("balance_dp.Models.InputParametrsList1", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlastFurnaceGasId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlastFurnaceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlowingParamsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("COCKsParamsPersentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CastIronElementsPercentsId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CastIronID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZHRMId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("BlastFurnaceGasId");

                    b.HasIndex("BlastFurnaceId");

                    b.HasIndex("BlowingParamsId");

                    b.HasIndex("COCKsParamsPersentId");

                    b.HasIndex("CastIronID");

                    b.HasIndex("SlagId");

                    b.HasIndex("ZHRMId");

                    b.ToTable("InputIndicators");
                });

            modelBuilder.Entity("balance_dp.Models.InputParametrsList2", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlusId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InputZRHMsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialConsuptionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("FlusId");

                    b.HasIndex("InputZRHMsID");

                    b.HasIndex("MaterialConsuptionId");

                    b.ToTable("InputMaterials");
                });

            modelBuilder.Entity("balance_dp.Models.InputZRM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A10_Aglomerat3ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A11_Aglomerat4ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A12_Aglomerat5ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A13_AglomeratNotClearedID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A14_AglomeratYamaID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A15_Okat_SokolovID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A16_Okat_LebedID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A17_Okat_KachkanID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A18_Okat_MikhayID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A19_Welding_slagID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A20_KorolekID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A21_Domen_prisadID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A22_Ruda_Mn_NizgulID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A23_Ruda_Mn_JairemID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A24_Aglomeran_screeningID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A25_ReserveID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("A9_Aglomerat2ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("A10_Aglomerat3ID");

                    b.HasIndex("A11_Aglomerat4ID");

                    b.HasIndex("A12_Aglomerat5ID");

                    b.HasIndex("A13_AglomeratNotClearedID");

                    b.HasIndex("A14_AglomeratYamaID");

                    b.HasIndex("A15_Okat_SokolovID");

                    b.HasIndex("A16_Okat_LebedID");

                    b.HasIndex("A17_Okat_KachkanID");

                    b.HasIndex("A18_Okat_MikhayID");

                    b.HasIndex("A19_Welding_slagID");

                    b.HasIndex("A20_KorolekID");

                    b.HasIndex("A21_Domen_prisadID");

                    b.HasIndex("A22_Ruda_Mn_NizgulID");

                    b.HasIndex("A23_Ruda_Mn_JairemID");

                    b.HasIndex("A24_Aglomeran_screeningID");

                    b.HasIndex("A25_ReserveID");

                    b.HasIndex("A9_Aglomerat2ID");

                    b.ToTable("InputZRM");
                });

            modelBuilder.Entity("balance_dp.Models.InputZRModels", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("B9_CastIronConsuption")
                        .HasColumnType("REAL");

                    b.Property<float>("C9_FE")
                        .HasColumnType("REAL");

                    b.Property<float>("D9_Fe0")
                        .HasColumnType("REAL");

                    b.Property<float>("E9_Fe2O3")
                        .HasColumnType("REAL");

                    b.Property<float>("F9_SiO2")
                        .HasColumnType("REAL");

                    b.Property<float>("G9_Al203")
                        .HasColumnType("REAL");

                    b.Property<float>("H9_CaO")
                        .HasColumnType("REAL");

                    b.Property<float>("I9_Mgo")
                        .HasColumnType("REAL");

                    b.Property<float>("J9_P")
                        .HasColumnType("REAL");

                    b.Property<float>("K9_S")
                        .HasColumnType("REAL");

                    b.Property<float>("L9_MnO")
                        .HasColumnType("REAL");

                    b.Property<float>("M9_Zn")
                        .HasColumnType("REAL");

                    b.Property<float>("N9_Pmpp")
                        .HasColumnType("REAL");

                    b.Property<float>("O9_H20")
                        .HasColumnType("REAL");

                    b.Property<float>("P9_TiO2")
                        .HasColumnType("REAL");

                    b.Property<float>("Q9_Cr")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("InputZRModels");
                });

            modelBuilder.Entity("balance_dp.Models.MaterialConsuption", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("A8_Fe")
                        .HasColumnType("REAL");

                    b.Property<float>("B8_FeO")
                        .HasColumnType("REAL");

                    b.Property<float>("C8_Fe2O3")
                        .HasColumnType("REAL");

                    b.Property<float>("D8_SiO2")
                        .HasColumnType("REAL");

                    b.Property<float>("E8_AlO3")
                        .HasColumnType("REAL");

                    b.Property<float>("F8_CaO")
                        .HasColumnType("REAL");

                    b.Property<float>("G8_MgO")
                        .HasColumnType("REAL");

                    b.Property<float>("H8_P")
                        .HasColumnType("REAL");

                    b.Property<float>("I8_S")
                        .HasColumnType("REAL");

                    b.Property<float>("J8_MnO")
                        .HasColumnType("REAL");

                    b.Property<float>("K8_Zn")
                        .HasColumnType("REAL");

                    b.Property<float>("L8_Pmpp")
                        .HasColumnType("REAL");

                    b.Property<float>("M8_H20")
                        .HasColumnType("REAL");

                    b.Property<float>("N8_TiO2")
                        .HasColumnType("REAL");

                    b.Property<float>("O8_Cr")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("MaterialConsuptions");
                });

            modelBuilder.Entity("balance_dp.Models.RegistrationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("balance_dp.Models.Slag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("list1_C49_SlagOutput")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C50_SulfurCapacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C51_HeatCapacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C53_CaO_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C54_SiO2_Caacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C55_Al2O3_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C56_MgO_Capacity")
                        .HasColumnType("REAL");

                    b.Property<float>("list1_C58_TiO2_Capacity")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Slags");
                });

            modelBuilder.Entity("balance_dp.Models.ZHRM", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("c69")
                        .HasColumnType("REAL");

                    b.Property<float>("c70")
                        .HasColumnType("REAL");

                    b.Property<float>("c71")
                        .HasColumnType("REAL");

                    b.Property<float>("c72_waterCapacity")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("ZHRMs");
                });

            modelBuilder.Entity("balance_dp.Models.COCKsParamsPersent", b =>
                {
                    b.HasOne("balance_dp.Models.COCKsAsh", "CocksAsh")
                        .WithMany()
                        .HasForeignKey("COCKsAshId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("balance_dp.Models.COCKsComposition", "CocksComposit")
                        .WithMany()
                        .HasForeignKey("COCKsCompositionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CocksAsh");

                    b.Navigation("CocksComposit");
                });

            modelBuilder.Entity("balance_dp.Models.DPInputData", b =>
                {
                    b.HasOne("balance_dp.Models.InputParametrsList2", "InputData2")
                        .WithMany()
                        .HasForeignKey("InputData2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("balance_dp.Models.InputParametrsList1", "InputIndicators")
                        .WithMany()
                        .HasForeignKey("InputIndicatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InputData2");

                    b.Navigation("InputIndicators");
                });

            modelBuilder.Entity("balance_dp.Models.Flus", b =>
                {
                    b.HasOne("balance_dp.Models.FlusModels", "Fluospat")
                        .WithMany()
                        .HasForeignKey("FluospatID");

                    b.HasOne("balance_dp.Models.FlusModels", "Limestone")
                        .WithMany()
                        .HasForeignKey("LimestoneID");

                    b.HasOne("balance_dp.Models.FlusModels", "Quartzite")
                        .WithMany()
                        .HasForeignKey("QuartziteID");

                    b.HasOne("balance_dp.Models.FlusModels", "Reserve")
                        .WithMany()
                        .HasForeignKey("ReserveID");

                    b.HasOne("balance_dp.Models.FlusModels", "Slug")
                        .WithMany()
                        .HasForeignKey("SlugID");

                    b.Navigation("Fluospat");

                    b.Navigation("Limestone");

                    b.Navigation("Quartzite");

                    b.Navigation("Reserve");

                    b.Navigation("Slug");
                });

            modelBuilder.Entity("balance_dp.Models.InputParametrsList1", b =>
                {
                    b.HasOne("balance_dp.Models.BlastFurnaceGas", "FurnaceGas")
                        .WithMany()
                        .HasForeignKey("BlastFurnaceGasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("balance_dp.Models.BlastFurnace", "BlastFur")
                        .WithMany()
                        .HasForeignKey("BlastFurnaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("balance_dp.Models.BlowingParams", "blowing")
                        .WithMany()
                        .HasForeignKey("BlowingParamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("balance_dp.Models.COCKsParamsPersent", "CockParam")
                        .WithMany()
                        .HasForeignKey("COCKsParamsPersentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("balance_dp.Models.CastIronElementsPercent", "CastIron")
                        .WithMany()
                        .HasForeignKey("CastIronID");

                    b.HasOne("balance_dp.Models.Slag", "slag")
                        .WithMany()
                        .HasForeignKey("SlagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("balance_dp.Models.ZHRM", "zhrm")
                        .WithMany()
                        .HasForeignKey("ZHRMId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlastFur");

                    b.Navigation("blowing");

                    b.Navigation("CastIron");

                    b.Navigation("CockParam");

                    b.Navigation("FurnaceGas");

                    b.Navigation("slag");

                    b.Navigation("zhrm");
                });

            modelBuilder.Entity("balance_dp.Models.InputParametrsList2", b =>
                {
                    b.HasOne("balance_dp.Models.Flus", "flus")
                        .WithMany()
                        .HasForeignKey("FlusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("balance_dp.Models.InputZRM", "InputZRHMs")
                        .WithMany()
                        .HasForeignKey("InputZRHMsID");

                    b.HasOne("balance_dp.Models.MaterialConsuption", "materialCons")
                        .WithMany()
                        .HasForeignKey("MaterialConsuptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("flus");

                    b.Navigation("InputZRHMs");

                    b.Navigation("materialCons");
                });

            modelBuilder.Entity("balance_dp.Models.InputZRM", b =>
                {
                    b.HasOne("balance_dp.Models.InputZRModels", "A10_Aglomerat3")
                        .WithMany()
                        .HasForeignKey("A10_Aglomerat3ID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A11_Aglomerat4")
                        .WithMany()
                        .HasForeignKey("A11_Aglomerat4ID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A12_Aglomerat5")
                        .WithMany()
                        .HasForeignKey("A12_Aglomerat5ID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A13_AglomeratNotCleared")
                        .WithMany()
                        .HasForeignKey("A13_AglomeratNotClearedID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A14_AglomeratYama")
                        .WithMany()
                        .HasForeignKey("A14_AglomeratYamaID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A15_Okat_Sokolov")
                        .WithMany()
                        .HasForeignKey("A15_Okat_SokolovID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A16_Okat_Lebed")
                        .WithMany()
                        .HasForeignKey("A16_Okat_LebedID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A17_Okat_Kachkan")
                        .WithMany()
                        .HasForeignKey("A17_Okat_KachkanID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A18_Okat_Mikhay")
                        .WithMany()
                        .HasForeignKey("A18_Okat_MikhayID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A19_Welding_slag")
                        .WithMany()
                        .HasForeignKey("A19_Welding_slagID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A20_Korolek")
                        .WithMany()
                        .HasForeignKey("A20_KorolekID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A21_Domen_prisad")
                        .WithMany()
                        .HasForeignKey("A21_Domen_prisadID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A22_Ruda_Mn_Nizgul")
                        .WithMany()
                        .HasForeignKey("A22_Ruda_Mn_NizgulID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A23_Ruda_Mn_Jairem")
                        .WithMany()
                        .HasForeignKey("A23_Ruda_Mn_JairemID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A24_Aglomeran_screening")
                        .WithMany()
                        .HasForeignKey("A24_Aglomeran_screeningID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A25_Reserve")
                        .WithMany()
                        .HasForeignKey("A25_ReserveID");

                    b.HasOne("balance_dp.Models.InputZRModels", "A9_Aglomerat2")
                        .WithMany()
                        .HasForeignKey("A9_Aglomerat2ID");

                    b.Navigation("A10_Aglomerat3");

                    b.Navigation("A11_Aglomerat4");

                    b.Navigation("A12_Aglomerat5");

                    b.Navigation("A13_AglomeratNotCleared");

                    b.Navigation("A14_AglomeratYama");

                    b.Navigation("A15_Okat_Sokolov");

                    b.Navigation("A16_Okat_Lebed");

                    b.Navigation("A17_Okat_Kachkan");

                    b.Navigation("A18_Okat_Mikhay");

                    b.Navigation("A19_Welding_slag");

                    b.Navigation("A20_Korolek");

                    b.Navigation("A21_Domen_prisad");

                    b.Navigation("A22_Ruda_Mn_Nizgul");

                    b.Navigation("A23_Ruda_Mn_Jairem");

                    b.Navigation("A24_Aglomeran_screening");

                    b.Navigation("A25_Reserve");

                    b.Navigation("A9_Aglomerat2");
                });
#pragma warning restore 612, 618
        }
    }
}
